src/cortxfs/cortxfs_ops.c

_[EOS-13606](https://jts.seagate.com/browse/EOS-13606):_
_Cthon:nfsidem test in special test suit is failing_
_In certain cases when we do a rename a file, node_id of a tree where this new file will be added is not initialized properly. We ended up adding this file to a random tree and hence while looking at expected location we are not finding this renamed file_
_Have modified cfs_rename API to initialize node_id of tree where a new node will be attached with valid node_id value_
_All UTs are passing_
_Able to create FS, mount FS and do basic I/O on that_
_Able to validated following test case manually after mounting FS_
1. _Create directory under mounted path_
2. _Create a file under mounted path_
3. _Move this file under created directory in step 1_
4. _Able to the file which we moved …

EOS-13606: Fixed nfsidem issue, issue with cfs_rename API

---

src/cortxfs/cortxfs_internal.c
src/include/cortxfs.h

_[EOS-11346](https://jts.seagate.com/browse/EOS-11346):_
_CORTXFS FSAL incorrectly handling multiple groups_
_CORTXFS code do not consider the passed on group list while checking access_
_Added code to parse the group list and determine the access_
NFS RPC passes the list of groups. Need to consider this list
while checking access on that file/directory.
https://github.com/Seagate/cortx-fs-ganesha/pull/21
_cthon test is passing Basic, General test cases_

EOS-11346 : Consider all groups while checking for access

---

src/cortxfs/CMakeLists.txt
src/cortxfs/cortxfs_fops.c
src/cortxfs/cortxfs_ops.c

commit e92e9216b4f498dc506df7471692383acdd81295
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Mon Sep 28 22:55:53 2020 -0600
EOS-8896: NFS ADDB: NFS-only tracepoints for READ (repo cortxfs)
List of modified files:
modified:   src/cortxfs/CMakeLists.txt
modified:   src/cortxfs/cortxfs_fops.c
modified:   src/cortxfs/cortxfs_ops.c
Change description:
Add new performance counters and integrate them further with other modules using newly added APIs
Addb APIs integration for read path
Unit test:
Compilation with and without ENABLE_TSDB_ADDB flag
Addb unit test while integrated with read handler
Regular UTs (both with and without ENABLE_TSDB_ADDB flag)
addb dump o/p from read handler after integration:
* …

EOS-8896: NFS ADDB: NFS-only tracepoints for READ (repo cortxfs)

---

src/cortxfs/cortxfs_ops.c

Problem Statement
EOS-13990: NFS ADDB: Tracepointsfor all ATTR operations
EOS-10522: NFS ADDB: Decoders for all file operations
Problem Description
Implement tracepoints and decoder for the attr handlers.
Solution Overview
Following changes has been done:
added wrapper over kvsfs_getattrs using kvsfs_perf_op_getattrs
Added traces for init and finish inside kvsfs_getattrs
Added traces for attributes like return code
added wrapper over kvsfs_setattrs using kvsfs_perf_op_setattrs
Added traces for init and finish inside kvsfs_setattrs
Added traces for attributes like return code
Added all enums in the decoder.
Unit Test Cases
`
sudo m0addb2dump -p /usr/lib64/libcortx-utils.so -- /addb_22028/o/100000000000000:2 | grep fsuser > addb_dump_op_decode_4
-bash-4.2$ cat addb_dump_op_decode_4 | grep …

EOS-13990: NFS ADDB: Tracepointsfor all ATTR operations

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_fops.c
src/cortxfs/cortxfs_internal.c
src/cortxfs/cortxfs_ops.c
src/include/cortxfs.h
src/include/cortxfs_fh.h

_[EOS-8996](https://jts.seagate.com/browse/EOS-8996):_
_EOS-NFS: Update the cfs_creat API to use FH_
_[EOS-7920](https://jts.seagate.com/browse/EOS-7920):_
_'nfs-ganesha' service getting down after executing simultaneous multiple Namespace operations with automation script._
_File creation APIs needed to be modified to work on FH_
_Because of recent change in FH, FH was dumping the stale stat to kvstore which leads to a problem of ganesha crashing_
_As FH is not present everywhere as of now I have created a temporary FH in start of cfs_mkdir, cfs_symlink, cfs_creat API and modified the rest of the functionality within these API to use FH. Once FH will be supplied from the caller to all of these three APIs temporary construction and destruction of FH will be removed. Along with these …

EOS-8996: Modified file creat path to use FH, fixed issue of FH dumping the stale stat attributes

---

src/cortxfscli/cortxfscli.py
src/cortxfscli/cortxfscli_validation_rules.json

Change description:
1)Data server parameter continued to get parsed when endpoints are created using cortxfscli script.
This parameter is unused in the code and can be removed.
1)Compiled the code and reinstalled the RPM
2)Ran the cortxfscli script with the following parameters
**cortxfscli endpoint create fs1 proto=nfs,secType=sys,Filesystem_id=192.1,client=1,clients=*,Squash=no_root_squash,access_type=RW,protocols=4,pnfs_enabled=false**
**This did not give any error.**
cortxfscli endpoint create fs1 proto=nfs,secType=sys,Filesystem_id=192.1,client=1,clients=*,Squash=no_root_squash,access_type=RW,protocols=4,pnfs_enabled=false,**data_server=10.230.242.6**
Using embedded validation rules
Traceback (most recent call last):
File …

EOS-14314:Cleanup unused data server parameter from cortxfscli

---

doc/RESTAPI_Guidelines.md

* JSON Error Response Schema :
To be consistent in returning errors(when using REST API) with other components
such as S3, we will follow the error format that S3 currently uses.
Link :
https://github.com/Seagate/cortx-fs/edit/EOS-13937/doc/RESTAPI_Guidelines.md
Signed-off-by: Deepak Mahale <deepak.mahale@seagate.com>

EOS-13937 : Rules for consistent error response format

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_ops.c
src/include/cortxfs_fh.h

_[EOS-9005](https://jts.seagate.com/browse/EOS-9005):_
_EOS-NFS: Update cfs_detach, and cfs_destroy_orphaned_file_
_With recent changes in FH we decided to supply a valid FH to all of the API in cortxfs wherever it is required, so that task was divided in further small task and as a part of that we have to modify cfs_detach and cfs_destroy_orphaned_file to use FH and optimize whatever was possible_
_As cfs_detach and cfs_destroy_orphaned_file were used by cortxfs API and FSAL code also so it was not directly possible to modify the signature of both of these API to pass FH as input parameter because we are not yet in a stage where we can pass a FH from FSAL code as it will have stale data. So with this limitation on both of these APIs I have created a temporary API where input will be FH …

EOS-9005:Modified cfs_detach and cfs_destroy_orphaned_file to use FH

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_ops.c

_[EOS-13992](https://jts.seagate.com/browse/EOS-13992):_
_ADDB Tracepoints-Directory Operations_
_Add ADDB tracepoints for Directory operations_
_Directory operations include, directory creation (mkdir), directory removal (rmdir), read the directory contents (readdir) and lookup a specific entry in directory (lookup). ADDB tracepoint added for function entry and points. This provides information on how much time the function / code snippet takes._
https://github.com/Seagate/cortx-utils/pull/48
https://github.com/Seagate/cortx-fs-ganesha/pull/40
https://github.com/Seagate/cortx-nsal/pull/23
_No new test cases added_
<details>
<summary>Click here to see the test execution output</summary>
```
[root@ssc-vm-c-0689 cortx-posix]# ./scripts/test.sh
--
--
Clean indexes …
```

EOS-13992: ADDB tracepoints for directory operations

---

src/tools/addb/scripts/addb2db_cortxfs.py
src/tools/addb/scripts/cortxfs_hist.py
src/tools/addb/scripts/cortxfs_req.py

commit b93363c1eb1dbe08baf44ec412307d2b347ad2c6
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Mon Oct 12 17:05:15 2020 -0600
EOS-13985:Implement nfs_req.py and hist.py <Part 1, cortxfs repo>
List of modified files:
modified:   src/tools/addb/scripts/addb2db_cortxfs.py
new file:   src/tools/addb/scripts/cortxfs_req.py
new file:   src/tools/addb/scripts/cortxfs_hist.py
Change description:
1. Add a python script named cortxfs_hist.py to generate histogram graphs with respect to operation and time from the perfor
2. Add a python script named cortxfs_req.py to generate performance call graph based on the o/p generated by addb2db_cortxfs
3. Update addb2db_cortxfs.py to track the operation id of immediate callers in map …

EOS-13985:Implement nfs_req.py and hist.py <cortxfs repo>

---

.github/workflows/triage.yml

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
Triage is an important part of open source. It can be difficult to keep up with the issues as the size of a project grows, the demands placed on the maintainers grow. This means they are forced to choose between spending enormous amounts of time reviewing each GitHub issue, only skimming over issues, or worse, ignoring issues.
Triage action can help an open-source project by labeling newly opened issues as `needs-triage`. So, maintainers could easily filter out all unattended/missed issues and label them appropriately in triage meetings. Now, it would be easy for a specific group of maintainers to filter out issues of their expertise/interest and start reviewing it in a timely manner.

[Github Action] Issue triage

---

src/fs/fs.c

EOS-14594: Fix the leaks found in cfs_fs_create and fs_ns_scan_cb
Problem Description:
Need to fix the leaks in cfs_fs_create and fs_ns_scan_cb.
Solution Overview:
1. Read the code in fs_ns_scan_cb and no fix is needed.
2. Fixed the leaks in cfs_fs_create.
Unit Test Cases:
1. UT passes.
2. nfs_posix test passes.
3. Cthon passes.
Signed-off-by: Shipra <shipra.gupta@seagate.com>

EOS-14594: Fix the leaks found in cfs_fs_create and fs_ns_scan_cb

---

src/test/ut/cortxfs_xattr_ops.h
src/test/ut/ut_cortxfs_xattr_ops.c

**Problem Description**
Unit test is failing for XATTR
**Solution Overview**
The issue was address of local variable was being referenced outside its host function.
**Unit Test Cases**
-bash-4.2$ sudo ./scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test
Tests passed = 17
Global KVS Tests
Total tests  = 4
Tests passed = 4 …

EOS-14672: Unit test is failing for XATTR

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_ops.c
src/include/cortxfs_fh.h

_[EOS-9004](https://jts.seagate.com/browse/EOS-9004):_
_EOS-NFS: Update cfs_unlink api and modify the internal apis to use FH_
_With recent changes in FH we decided to supply a valid FH to all of the API in cortxfs wherever it is required, so that task was divided in further small task and as a part of that we have to modify cfs_unlink API to use FH and optimize whatever was possible_
_Have modified cfs_unlink API to construct the FH based on given inode as input param and use it for further logic inside this API_
- _All UTs are passing - Check the log in Testing section_
- _Cthon is passing  - Check the log in Testing section_
- _Able to create FS, mount FS and do basic I/O on that_
_I have mounted /var/motr separately in order to avoid /var/motr is getting 100% full_
<details> …

EOS-9004: Modified cfs_unlink to use FH

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_fops.c
src/cortxfs/cortxfs_ops.c
src/include/cfs_perfc.h

_[EOS-14572](https://jts.seagate.com/browse/EOS-14572):_
_ADDB : Code refactor_
_Refactoring code for ADDB_
_Refactor function tags, maps and attribute enums and move out repo specific code. Introduce ranges. move out plugin._
_Build, UT and cthon testing_
<details>
<summary>Click here to see the test execution output</summary>
```
[root@ssc-vm-c-0689 cortx-posix-new]# ./scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test …
```

EOS-14572: ADDB : Code refactor (cortxfs repo)

---

src/tools/addb/scripts/addb2db_cortxfs.py
src/tools/addb/scripts/cortxfs_hist.py
src/tools/addb/scripts/cortxfs_req.py

[root@ssc-vm-c-0040 /]# ./cortx-posix/scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test
Tests passed = 17
Global KVS Tests
Total tests  = 4
Tests passed = 4
CORTXFS Unit tests
Endpoint ops Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
Total …

EOS-13996:ADDB:Profiling for all I/O operations (cortxfs repo)

---

src/cortxfs/cortxfs_fh.c
src/cortxfs/cortxfs_fops.c

_[EOS-9009](https://jts.seagate.com/browse/EOS-9009):_
_EOS-NFS: Update I/O ops to a file using FH_
_With recent changes in FH we decided to supply a valid FH to all of the API in cortxfs wherever it is required, so that task was divided in further small task and as a part of that we have to modify cfs_write, cfs_read and cfs_truncate API to use FH and optimize whatever was possible_
_Have modified cfs_write, cfs_read and cfs_truncate API to construct the FH based on given inode as input param and use it for further logic inside this API_
- _All UTs are passing - attached the log in Testing section below_
- _Cthon is passing  - attached the log in Testing section below_
- _Able to create FS, mount FS and do basic I/O on that_
_I have mounted /var/motr separately in order to avoid …

EOS-9009: Updated cfs_read cfs_write and cfs_truncate to use FH

---

src/CMakeLists.txt
src/test/ut/ut_cortxfs_xattr_file_ops.c

[root@ssc-vm-c-0040 /]# ./cortx-posix/scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test
Tests passed = 17
Global KVS Tests
Total tests  = 4
Tests passed = 4
CORTXFS Unit tests
Endpoint ops Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
Total …

EOS-14772: Perfc APIs to detect uninitialized TLS (repo cortxfs)

---

src/cortxfs/cortxfs_fops.c
src/cortxfs/cortxfs_internal.c
src/cortxfscli/cortxfscli.py
src/cortxfscli/cortxfscli_validation_rules.json
src/fs/fs.c
src/include/cortxfs.h
src/include/internal/fs.h
src/management/fs.c
src/test/ut/ut_cortxfs_endpoint_ops.c
src/test/ut/ut_cortxfs_fs_ops.c
src/test/ut/ut_cortxfs_helper.c

[root@ssc-vm-c-0040 /]# ./cortx-posix/scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test
Tests passed = 17
Global KVS Tests
Total tests  = 4
Tests passed = 4
CORTXFS Unit tests
Endpoint ops Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
Total …

EOS-15064: cortxfs perf: Expose bsize as a per file system configurable param and stop using m0store_get_bsize (repo cortxfs)

---

src/include/internal/error_handler.h
src/management/error_handler.c
src/management/fs.c

_[EOS-13969](https://jts.seagate.com/browse/EOS-13969):_
_fs REST API error response changes for DELETE(DELETE http method) request_
Integrated error response framework with fs delete API.
A mapping function was required to map the UNIX error code returned underlying infrastructure(cortxfs (CFS) layer) to appropriate error response ids.
These error response ids would in turn map with respective error messages.
Also handled the case for etags and mismatch of hashes.
Implemented the mapping structure which maps the error code to respective error response messages.
Tested with curl command
```
1. trying to delete a filesystem when its is exported already
723986@ssc-vm-c-0219.colo.seagate.com:/home/723986/rpmbuild/RPMS/x86_64
$ curl -v -X DELETE "http://localhost:8081/fs/fs7" -H  "accept: …
```

EOS-13969: Implemented error handling for fs_delete REST API

---

src/cortxfs/cortxfs_fops.c
src/cortxfs/cortxfs_ops.c
src/include/cortxfs.h
src/test/ut/ut_cortxfs_attr_ops.c
src/test/ut/ut_cortxfs_dir_ops.c
src/test/ut/ut_cortxfs_link_ops.c

_[EOS-9010](https://jts.seagate.com/browse/EOS-9010):_
_File handle support for cortxfs API's_
_The current implementation relies on cfs_fs and inode, that should be eliminated_
_Modified relevant API's to use FH_
_Build, UT testing, ensure no errors_
<details>
<summary>Click here to see the script test output</summary>
```
[root@ssc-vm-c-1561 cortx-posix-9010]# ./scripts/test.sh
--
--
NS Tests
Iterator test
KVTree test
Tests …
```

EOS-9010: File handle support for cortxfs API's (cortx-fs repo)
